# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb2c7c9e6bc92b0d44b66eb8cfdd72a6f614ad0bf887087aaccb58e749e422761691d50e12e5cb42f2523857ef7ce04b5207feb4129fa8226cfd8f950c37d68

test:
  secret_key_base: ba55b3ed6247da5b7bbe303055fe04e5eb115a2a39977cc6c8118704ce51bcc9c89bfe7ee290abc1755914700b317d644da4b35d6dd4212e4cdbba3ee9e0c181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
